
dist: xenial

language: python

python:
  - "3.6"

install:
  - sudo apt update
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt install -y gdal-bin libgdal-dev python3-gdal binutils libproj-dev gunicorn
  - sudo apt install -y postgresql-9.6-postgis-2.4
  - pip install -r requirements.txt
  - pip install codecov

services: postgresql

before_script:
  - psql -c "CREATE DATABASE django_travis_test;" -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres

script:
  - python manage.py migrate
  - coverage run ./manage.py test

after_success:
  - codecov