
dist: xenial

addons:
  postgresql: 11
  apt:
    packages:
    - postgresql-11-postgis-2.5

language: python

python:
  - "3.6"

install:
  - sudo apt update
  - sudo apt install -y gdal-bin libgdal-dev python3-gdal binutils libproj-dev gunicorn
  - pip install -r requirements.txt
  - pip install codecov

services: postgresql

before_script:
  - psql -c "CREATE DATABASE django_travis_test;" -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres

script:
  - python manage.py migrate

after_success:
  - codecov