# Generated by Django 2.2 on 2019-05-06 19:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=markdownx.models.MarkdownxField(default=None),
            preserve_default=False,
        ),
    ]
