# Generated by Django 2.1.7 on 2019-04-10 21:05

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bistro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='BistroPlace',
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='BistroType',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
