# Generated by Django 2.1.7 on 2019-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0002_auto_20190324_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_hash',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
