# Generated by Django 2.1.7 on 2019-03-24 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0004_activity_related_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_hash',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.AddField(
            model_name='activity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
