# Generated by Django 2.1.7 on 2019-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0005_auto_20190324_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
