# Generated by Django 2.1.7 on 2019-03-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_logger', '0007_add_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='related_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('slug', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='establishment',
            unique_together={('slug', 'user')},
        ),
    ]
